# Generated by Django 3.1.7 on 2021-05-01 07:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgflipMemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loves', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgflip_type', models.CharField(default='', max_length=100)),
                ('imgflip_url', models.CharField(default='', max_length=300)),
                ('imgflip_post', models.CharField(default='', max_length=300)),
                ('imgflip_views', models.PositiveIntegerField(default=0, null=True)),
                ('imgflip_img_votes', models.IntegerField(default=0, null=True)),
                ('imgflip_title', models.CharField(default='', max_length=300, null=True)),
                ('imgflip_author', models.CharField(default='', max_length=150, null=True)),
                ('imgflip_boxes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=None, null=True, size=None)),
                ('loves', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('rating_letters', models.CharField(default='', max_length=5)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=None, null=True, size=None)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UploadMeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme', models.FileField(upload_to='memes/static/memes/images')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=500)),
                ('url', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(default='her', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemesComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_position', models.IntegerField(default=0)),
                ('body', models.CharField(default='', max_length=150)),
                ('loves', models.IntegerField(default=0)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.imgflipmemes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
