# Generated by Django 3.1.7 on 2021-05-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memescomments',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='memescomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='ImgflipMemes',
        ),
        migrations.DeleteModel(
            name='MemesComments',
        ),
    ]
