# Generated by Django 3.1.7 on 2021-05-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_pic'),
        ('memes', '0002_auto_20210501_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgflipMemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loves', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='MemesComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meme_position', models.IntegerField(default=0)),
                ('body', models.CharField(default='', max_length=150)),
                ('loves', models.IntegerField(default=0)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memes.imgflipmemes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
