# Generated by Django 3.1.7 on 2021-04-08 08:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShortedList',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shortedids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='StupidStuffJokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.CharField(default='', max_length=65000)),
                ('category', models.CharField(default='', max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('loves', models.IntegerField(default=0)),
                ('rating_letters', models.CharField(default='', max_length=5)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UploadJokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('tag', models.CharField(default='normal', max_length=100)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WockaJokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=65000)),
                ('author', models.CharField(max_length=100)),
                ('loves', models.IntegerField(default=0)),
                ('funney', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('rating_letters', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default=None, max_length=150)),
                ('loves', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('wockajokes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokes.wockajokes')),
            ],
        ),
    ]
