# Generated by Django 3.1.7 on 2021-04-08 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditJokes',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('body', models.CharField(default='', max_length=50000)),
                ('score', models.FloatField(default=0)),
                ('title', models.CharField(default='', max_length=350)),
                ('loves', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
