# Generated by Django 3.1.7 on 2021-04-22 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_redditjokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsurdlyBigJokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('body', models.CharField(max_length=2500)),
                ('author', models.CharField(default='', max_length=100)),
                ('loves', models.IntegerField(default=0)),
                ('funney', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('rating_letters', models.CharField(max_length=5)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
