# Generated by Django 3.1.7 on 2021-05-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_absurdlybigjokes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJokes',
        ),
    ]
