# Generated by Django 3.1.7 on 2021-05-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0005_uploadjokes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJokes',
        ),
    ]
