# Generated by Django 3.1.7 on 2021-05-22 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile_pic'),
        ('jokes', '0006_delete_uploadjokes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadJokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=5000)),
                ('category', models.CharField(default=None, max_length=100, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('tag', models.CharField(default=None, max_length=100, null=True)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
