# Generated by Django 3.1.7 on 2021-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ananomyous_username',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
