# Generated by Django 3.1.7 on 2021-05-23 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_auto_20210522_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='ananomyous_username',
            new_name='username',
        ),
        migrations.AddField(
            model_name='feedback',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
