# Generated by Django 3.1.7 on 2021-05-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_auto_20210523_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
