# Generated by Django 3.1.7 on 2021-05-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0013_auto_20210530_0400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbacks',
        ),
    ]
