# Generated by Django 3.1.7 on 2021-06-06 04:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0015_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jokes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default=None, max_length=100)),
                ('source_id', models.IntegerField(default=None)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=65000)),
                ('author', models.CharField(default=None, max_length=100)),
                ('loves', models.IntegerField(default=0)),
                ('funney', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('rating_letters', models.CharField(max_length=5)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=None, null=True, size=None)),
                ('category', models.CharField(max_length=100)),
                ('shares', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
    ]
