# Generated by Django 3.1.7 on 2021-06-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0016_jokes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='source',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
