# Generated by Django 3.1.7 on 2021-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0017_auto_20210606_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokes',
            name='author',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jokes',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jokes',
            name='source_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
