# Generated by Django 3.1.7 on 2021-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0019_jokecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokecomments',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
