# Generated by Django 3.1.7 on 2021-06-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0024_auto_20210616_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokes',
            old_name='rating',
            new_name='rating_letters_points',
        ),
    ]
