# Generated by Django 3.1.7 on 2021-06-19 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0025_auto_20210619_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jokes',
            old_name='funney',
            new_name='rating',
        ),
    ]
